h=plot(rand(10,2));
% Legend
lh=legend(h,'First','Second');
set(lh,'position',get(lh,'position').*[1 0.95 1 1.5],...
        'YLim',get(lh,'ylim').*[1 1.5])
txh = text(0.5,max(get(lh,'yli m')),'{\bf Lines}',...
                'Parent',lh,'VerticalAlign','top',...
                'HorizontalAlign','center')